/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Aptos', 'Segoe UI Variable', 'Segoe UI', 'system-ui', '-apple-system', 'sans-serif'],
      },
      colors: {
        // Design System Colors mapping to CSS Variables
        'neutral-primary-soft': 'var(--neutral-primary-soft)',
        'neutral-primary': 'var(--neutral-primary)',
        'neutral-primary-medium': 'var(--neutral-primary-medium)',
        'neutral-primary-strong': 'var(--neutral-primary-strong)',
        'neutral-secondary-soft': 'var(--neutral-secondary-soft)',
        'neutral-secondary': 'var(--neutral-secondary)',
        'neutral-secondary-medium': 'var(--neutral-secondary-medium)',
        'neutral-secondary-strong': 'var(--neutral-secondary-strong)',
        'neutral-tertiary-soft': 'var(--neutral-tertiary-soft)',
        'neutral-tertiary': 'var(--neutral-tertiary)',
        'neutral-tertiary-medium': 'var(--neutral-tertiary-medium)',
        'neutral-quaternary': 'var(--neutral-quaternary)',
        'quaternary-medium': 'var(--quaternary-medium)',
        'gray': 'var(--gray)',
        
        'brand-softer': 'var(--brand-softer)',
        'brand-soft': 'var(--brand-soft)',
        'brand': 'var(--brand)',
        'brand-medium': 'var(--brand-medium)',
        'brand-strong': 'var(--brand-strong)',
        
        'success-soft': 'var(--success-soft)',
        'success': 'var(--success)',
        'success-medium': 'var(--success-medium)',
        'success-strong': 'var(--success-strong)',
        
        'danger-soft': 'var(--danger-soft)',
        'danger': 'var(--danger)',
        'danger-medium': 'var(--danger-medium)',
        'danger-strong': 'var(--danger-strong)',
        
        'warning-soft': 'var(--warning-soft)',
        'warning': 'var(--warning)',
        'warning-medium': 'var(--warning-medium)',
        'warning-strong': 'var(--warning-strong)',
        
        'dark': 'var(--dark)',
        'dark-strong': 'var(--dark-strong)',
        'disabled': 'var(--disabled)',
        
        'heading': 'var(--heading)',
        'body': 'var(--body)',
        'body-subtle': 'var(--body-subtle)',
        
        'fg-brand-subtle': 'var(--fg-brand-subtle)',
        'fg-brand': 'var(--fg-brand)',
        'fg-brand-strong': 'var(--fg-brand-strong)',
        
        'fg-success': 'var(--fg-success)',
        'fg-success-strong': 'var(--fg-success-strong)',
        'fg-danger': 'var(--fg-danger)',
        'fg-danger-strong': 'var(--fg-danger-strong)',
        'fg-warning-subtle': 'var(--fg-warning-subtle)',
        'fg-warning': 'var(--fg-warning)',
        'fg-disabled': 'var(--fg-disabled)',

        'border-dark': 'var(--border-dark)',
        'border-buffer': 'var(--border-buffer)',
        'border-buffer-medium': 'var(--border-buffer-medium)',
        'border-buffer-strong': 'var(--border-buffer-strong)',
        'border-muted': 'var(--border-muted)',
        'border-light-subtle': 'var(--border-light-subtle)',
        'border-light': 'var(--border-light)',
        'border-light-medium': 'var(--border-light-medium)',
        'border-default-subtle': 'var(--border-default-subtle)',
        'border-default': 'var(--border-default)',
        'border-default-medium': 'var(--border-default-medium)',
        'border-default-strong': 'var(--border-default-strong)',
        'border-success-subtle': 'var(--border-success-subtle)',
        'border-success': 'var(--border-success)',
        'border-danger-subtle': 'var(--border-danger-subtle)',
        'border-danger': 'var(--border-danger)',
        'border-warning-subtle': 'var(--border-warning-subtle)',
        'border-warning': 'var(--border-warning)',
        'border-brand-subtle': 'var(--border-brand-subtle)',
        'border-brand-light': 'var(--border-brand-light)',
        'border-brand': 'var(--border-brand)',
        'border-dark-subtle': 'var(--border-dark-subtle)',
        'border-purple': 'var(--border-purple)',
        'border-orange': 'var(--border-orange)',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'default': 'var(--radius-default)',
        'base': 'var(--radius-base)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        '2xs': 'var(--shadow-2xs)',
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.5s cubic-bezier(0.32,0.72,0,1) both',
        'fade-in': 'fade-in 0.4s cubic-bezier(0.32,0.72,0,1) both',
      },
    },
  },
  plugins: [],
};
